name: 同步上游代码与所有Tag
on:
  workflow_dispatch:

jobs:
  sync_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 同步所有分支与标签
        uses: repo-sync/github-sync@v2
        with:
          source_repo: X1a0He/X1a0HeWeChatPlugin
          source_branch: ""
          destination_branch: ""
          github_token: ${{ secrets.UPSTREAM_TOKEN }}
          sync_tags: true
